[package]
name = "service_registry_client"
version = "0.1.0"
authors = ["Miguel Pérez García <miguelpg_95@hotmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.16"
uuid = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"